### ISSUE TITLE
[Website] Error while uploading image

### ISSUE THREAD

**Issue by TheAifam5** [OscarHolst/UnixPorn#2]
File is uploaded but server returns: "Error while uploading image!"

**Comment by OscarHolst** [comment]
Pardon the delay. How do you know the file is uploaded if you get error message? What file format and file size are you trying to upload? Did the image name contain any "strange" characters? As much information as possible makes it easier to understand the issue here.

**Comment by TheAifam5** [comment]
Resolution: 1920x1080
Size: 2.9MB
Format: PNG
Image name: image.png
I dont know, I'm guessing xd

![image](https://cloud.githubusercontent.com/assets/2192274/16996027/a7554a0a-4eaf-11e6-8086-296ce4252ce7.png)

**Comment by OscarHolst** [comment]
Thanks for answers, what browser did you use? Have you tried another browser?

**Comment by TheAifam5** [comment]
Chrome.
Ok i will try again.

**Comment by OscarHolst** [comment]
Hello again, i have recently updated most of the code on the website and improved the upload script, feel free to try again. Also note that it's no longer unixporn.org but the new name: https://www.nixplorer.org 

Have a nice day!
